"use client";

import { Sparkles, Smile, Frown, Meh } from "lucide-react";
import type { AnalysisResult, ScrapedComment } from "../tool-job-utils";
import {
  RatioVisualizer,
  MultiLabelVisualizer,
  AccordionVisualizer,
} from "../visualizer-strategies";

type JobAiAnalysisProps = {
  analysis: AnalysisResult;
  comments: ScrapedComment[];
};

export function JobAiAnalysis({ analysis, comments }: JobAiAnalysisProps) {
  const sentiment = String(analysis.sentiment || "").toLowerCase();

  return (
    <div className="bg-slate-50/50 rounded-2xl border border-slate-100 p-3.5 space-y-3.5">
      {/* Unified Premium AI Digest Card */}
      <div className="bg-gradient-to-br from-brand/5 via-white to-brand-strong/5 border border-brand/10 rounded-xl p-3.5 space-y-3 shadow-xs relative overflow-hidden">
        {/* Decorative background aura glow */}
        <div className="absolute top-0 right-0 w-32 h-32 bg-brand/10 rounded-full blur-3xl pointer-events-none -mr-8 -mt-8" />

        <div className="flex items-center justify-between min-w-0 relative z-10">
          <div className="flex items-center gap-2">
            <div className="p-1.5 bg-gradient-to-tr from-brand to-brand-strong text-white rounded-lg shadow-sm shrink-0">
              <Sparkles className="size-3.5 animate-pulse" />
            </div>
            <div className="min-w-0">
              <h4 className="text-[11px] font-extrabold text-slate-900 tracking-tight block">
                AI Summary
              </h4>
              <span className="text-[9px] text-slate-400 font-medium block leading-none">
                Smart digest generated by AI Engine
              </span>
            </div>
          </div>

          {/* Elegant Brand pill badge */}
          <div className="shrink-0 bg-brand/5 text-brand font-bold px-2 py-0.5 rounded-full text-[8.5px] uppercase tracking-wider border border-brand/10">
            AI Powered
          </div>
        </div>

        {/* Content text */}
        <div className="text-[11px] text-slate-700 leading-relaxed font-medium relative z-10 pt-0.5">
          {analysis.summary || "No summary available."}
        </div>
      </div>

      {/* Sentiment and visualizers stacked beautifully */}
      <div className="space-y-3">
        {analysis.sentiment && (
          <div className="flex items-center justify-between border-b border-slate-100/60 pb-2">
            <span className="text-[9px] font-bold text-slate-400 uppercase tracking-widest">
              Sentiment Analysis
            </span>
            {(() => {
              if (sentiment === "positive") {
                return (
                  <div className="flex items-center gap-1.5 px-2.5 py-0.5 bg-emerald-500 text-white border border-emerald-400 rounded-full text-[9.5px] font-extrabold uppercase shadow-xs shadow-emerald-500/20 select-none animate-bounce-slow">
                    <Smile className="size-3 text-white" />
                    <span>Positive</span>
                  </div>
                );
              }
              if (sentiment === "negative") {
                return (
                  <div className="flex items-center gap-1.5 px-2.5 py-0.5 bg-rose-500 text-white border border-rose-450 rounded-full text-[9.5px] font-extrabold uppercase shadow-xs shadow-rose-500/20 select-none animate-bounce-slow">
                    <Frown className="size-3 text-white" />
                    <span>Negative</span>
                  </div>
                );
              }
              return (
                <div className="flex items-center gap-1.5 px-2.5 py-0.5 bg-slate-600 text-white border border-slate-500 rounded-full text-[9.5px] font-extrabold uppercase shadow-xs shadow-slate-600/10 select-none">
                  <Meh className="size-3 text-white" />
                  <span>{analysis.sentiment}</span>
                </div>
              );
            })()}
          </div>
        )}

        {/* Keywords Hashdeck */}
        <div className="flex flex-wrap gap-1 pb-1">
          {Array.isArray(analysis.keywords) && analysis.keywords.length > 0 ? (
            analysis.keywords.map((kw: string, i: number) => (
              <span
                key={i}
                className="px-1.5 py-0.5 bg-white border border-slate-200 text-slate-500 rounded-md text-[9px] font-semibold hover:border-brand/30 hover:text-brand transition-colors cursor-default shadow-xs"
              >
                #{kw}
              </span>
            ))
          ) : (
            <span className="text-[9px] text-slate-400 italic">
              No keywords available
            </span>
          )}
        </div>

        {/* Visualizers Stack */}
        {analysis.intentRatios && (
          <div className="pt-4 border-t border-slate-100">
            <RatioVisualizer intentRatios={analysis.intentRatios} />
          </div>
        )}

        {analysis.postType && (
          <div className="pt-4 border-t border-slate-100">
            <MultiLabelVisualizer
              postType={analysis.postType}
              commentThemes={analysis.commentThemes}
            />
          </div>
        )}

        {analysis.politicians && (
          <div className="pt-4 border-t border-slate-100">
            <AccordionVisualizer
              politicians={analysis.politicians}
              comments={comments}
            />
          </div>
        )}
      </div>
    </div>
  );
}
