"use client";

import { Sparkles, Smile, Frown, Meh, Activity, Database, Info } from "lucide-react";
import { cn } from "@/lib/utils";
import {
  formatAnalysisConfidence,
  getAnalysisClassificationLabel,
  getAnalysisDisplayBlocks,
  type AnalysisDisplayPreset,
  hasIntentAnalysisPayload,
  type AnalysisResult,
  type ScrapedComment,
} from "../tool-job-utils";
import { AnalysisBlockEntry } from "./visualizer/analysis-block-entry";
import {
  RatioVisualizer,
  MultiLabelVisualizer,
  AccordionVisualizer,
} from "../visualizer-strategies";

type JobAiAnalysisProps = {
  analysis: AnalysisResult;
  comments: ScrapedComment[];
  schemaHintKeys?: string[];
  analysisDisplayPreset?: AnalysisDisplayPreset;
};

export function JobAiAnalysis({
  analysis,
  comments,
  schemaHintKeys = [],
  analysisDisplayPreset,
}: JobAiAnalysisProps) {
  const sentiment = String(analysis.sentiment || "").toLowerCase();
  const hasIntentPayload = hasIntentAnalysisPayload(analysis);
  const classification = getAnalysisClassificationLabel(analysis);
  const confidence = formatAnalysisConfidence(analysis.confidence_score);
  const purchaseSignal = analysis?.purchase_intent === 'interested'
    ? true
    : analysis?.purchase_intent === 'disinterested' ? false : (analysis?.purchase_intent_signal as boolean | undefined);

  const showClassification = !!classification;
  const showConfidence = confidence !== null && confidence !== undefined;
  const showPurchaseSignal = purchaseSignal === true || purchaseSignal === false;
  const visibleBoxesCount = [showClassification, showConfidence, showPurchaseSignal].filter(Boolean).length;

  const dynamicBlocks = getAnalysisDisplayBlocks(
    analysis,
    schemaHintKeys,
    analysisDisplayPreset,
  );
  const summary =
    analysis.summary_of_intent || analysis.summary || "No summary available.";

  return (
    <div className="bg-slate-50/50 rounded-2xl border border-slate-100 p-3.5 space-y-3.5">
      {/* Unified Premium AI Digest Card */}
      <div className="bg-linear-to-br from-brand/5 via-white to-brand-strong/5 border border-brand/10 rounded-xl p-3.5 space-y-3 shadow-xs relative overflow-hidden">
        {/* Decorative background aura glow */}
        <div className="absolute top-0 right-0 w-32 h-32 bg-brand/10 rounded-full blur-3xl pointer-events-none -mr-8 -mt-8" />

        <div className="flex items-center justify-between min-w-0 relative z-10">
          <div className="flex items-center gap-2">
            <div className="p-1.5 bg-linear-to-tr from-brand to-brand-strong text-white rounded-lg shadow-sm shrink-0">
              <Sparkles className="size-3.5 animate-pulse" />
            </div>
            <div className="min-w-0">
              <h4 className="text-[11px] font-extrabold text-slate-900 tracking-tight block">
                AI Summary
              </h4>
              <span className="text-[9px] text-slate-400 font-medium block leading-none">
                Smart digest generated by AI Engine
              </span>
            </div>
          </div>

          {/* Elegant Brand pill badge */}
          <div className="shrink-0 bg-brand/5 text-brand font-bold px-2 py-0.5 rounded-full text-[8.5px] uppercase tracking-wider border border-brand/10">
            AI Powered
          </div>
        </div>

        {/* Content text */}
        <div className="text-[11px] text-slate-700 leading-relaxed font-medium relative z-10 pt-0.5">
          {summary}
        </div>
      </div>

      {/* Sentiment and visualizers stacked beautifully */}
      <div className="space-y-3">
        {hasIntentPayload && visibleBoxesCount > 0 && (
          <div className="flex flex-wrap gap-2.5">
            {showClassification && (
              <div className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 shadow-xs flex-1 sm:flex-initial sm:min-w-[180px] sm:max-w-[240px]">
                <p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">
                  Classification
                </p>
                <p className="mt-1 text-sm font-black leading-tight text-slate-800">
                  {classification}
                </p>
              </div>
            )}
            {showConfidence && (
              <div className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 shadow-xs flex-1 sm:flex-initial sm:min-w-[180px] sm:max-w-[240px]">
                <p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">
                  Confidence
                </p>
                <p className="mt-1 text-sm font-black leading-tight text-slate-800">
                  {confidence}
                </p>
              </div>
            )}
            {showPurchaseSignal && (
              <div className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 shadow-xs flex-1 sm:flex-initial sm:min-w-[180px] sm:max-w-[240px]">
                <p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">
                  Purchase Signal
                </p>
                <p className="mt-1 text-sm font-black leading-tight text-slate-800">
                  {purchaseSignal === true ? "Yes" : "No"}
                </p>
              </div>
            )}
          </div>
        )}

        {analysis.sentiment && (
          <div className="flex items-center justify-between border-b border-slate-100/60 pb-2">
            <span className="text-[9px] font-bold text-slate-400 uppercase tracking-widest">
              Sentiment Analysis
            </span>
            {(() => {
              if (sentiment === "positive") {
                return (
                  <div className="flex items-center gap-1.5 px-2.5 py-0.5 bg-emerald-500 text-white border border-emerald-400 rounded-full text-[9.5px] font-extrabold uppercase shadow-xs shadow-emerald-500/20 select-none animate-bounce-slow">
                    <Smile className="size-3 text-white" />
                    <span>Positive</span>
                  </div>
                );
              }
              if (sentiment === "negative") {
                return (
                  <div className="flex items-center gap-1.5 px-2.5 py-0.5 bg-rose-500 text-white border border-rose-450 rounded-full text-[9.5px] font-extrabold uppercase shadow-xs shadow-rose-500/20 select-none animate-bounce-slow">
                    <Frown className="size-3 text-white" />
                    <span>Negative</span>
                  </div>
                );
              }
              return (
                <div className="flex items-center gap-1.5 px-2.5 py-0.5 bg-slate-600 text-white border border-slate-500 rounded-full text-[9.5px] font-extrabold uppercase shadow-xs shadow-slate-600/10 select-none">
                  <Meh className="size-3 text-white" />
                  <span>{analysis.sentiment}</span>
                </div>
              );
            })()}
          </div>
        )}

        {/* Keywords Hashdeck */}
        <div className="flex flex-wrap gap-1 pb-1">
          {Array.isArray(analysis.keywords) && analysis.keywords.length > 0 ? (
            analysis.keywords.map((kw: string, i: number) => (
              <span
                key={i}
                className="px-1.5 py-0.5 bg-white border border-slate-200 text-slate-500 rounded-md text-[9px] font-semibold hover:border-brand/30 hover:text-brand transition-colors cursor-default shadow-xs"
              >
                #{kw}
              </span>
            ))
          ) : (
            <span className="text-[9px] text-slate-400 italic">
              No keywords available
            </span>
          )}
        </div>

        {dynamicBlocks.length > 0 && (
          <div className="relative space-y-6 pl-6 before:absolute before:left-1.5 before:top-2 before:bottom-2 before:w-0.5 before:bg-slate-150/70 before:rounded-full pt-1">
            {dynamicBlocks.map((block) => {
              const isSummary = block.id === "summary";
              const isMetrics = block.id === "metrics";
              const isEvidence = block.id === "evidence";

              const theme = isSummary
                ? {
                  border: "border-l-3 border-l-violet-500 border-y-slate-200/60 border-r-slate-200/60",
                  bg: "bg-linear-to-b from-violet-500/[0.015] to-white/40",
                  titleColor: "text-violet-750",
                  icon: Sparkles,
                  dot: "bg-violet-500 ring-4 ring-violet-50/50",
                }
                : isMetrics
                  ? {
                    border: "border-l-3 border-l-amber-500 border-y-slate-200/60 border-r-slate-200/60",
                    bg: "bg-linear-to-b from-amber-500/[0.015] to-white/40",
                    titleColor: "text-amber-750",
                    icon: Activity,
                    dot: "bg-amber-500 ring-4 ring-amber-50/50",
                  }
                  : isEvidence
                    ? {
                      border: "border-l-3 border-l-emerald-500 border-y-slate-200/60 border-r-slate-200/60",
                      bg: "bg-linear-to-b from-emerald-500/[0.015] to-white/40",
                      titleColor: "text-emerald-750",
                      icon: Database,
                      dot: "bg-emerald-500 ring-4 ring-emerald-50/50",
                    }
                    : {
                      border: "border-l-3 border-l-sky-500 border-y-slate-200/60 border-r-slate-200/60",
                      bg: "bg-linear-to-b from-sky-500/[0.015] to-white/40",
                      titleColor: "text-sky-750",
                      icon: Info,
                      dot: "bg-sky-500 ring-4 ring-sky-50/50",
                    };

              const HeaderIcon = theme.icon;

              return (
                <section
                  key={block.id}
                  className={cn(
                    "rounded-2xl border p-5 shadow-2xs hover:shadow-xs transition-all duration-300 space-y-4 bg-white relative",
                    theme.border,
                    theme.bg
                  )}
                >
                  <div className={cn("absolute -left-[21px] top-[24px] size-2.5 rounded-full border border-white z-10 shadow-3xs", theme.dot)} />
                  <div className="flex items-center gap-2 pb-2.5 border-b border-slate-100">
                    <HeaderIcon className={cn("size-4 shrink-0", theme.titleColor)} />
                    <div className="space-y-0.5">
                      <h4 className={cn("text-xs font-extrabold uppercase tracking-wider leading-none", theme.titleColor)}>
                        {block.title}
                      </h4>
                      <p className="text-[10px] font-medium text-slate-400">
                        {block.description}
                      </p>
                    </div>
                  </div>

                  {/* Grid with dynamic columns layout */}
                  {(() => {
                    const isSingleCol =
                      block.entries.length === 1 ||
                      block.entries.some((entry) => {
                        const isLongVal =
                          typeof entry.value === "string" &&
                          (entry.value.length > 150 || entry.value.includes("\n"));
                        return (
                          isLongVal ||
                          entry.valueType === "object" ||
                          entry.valueType === "array"
                        );
                      });

                    return (
                      <div
                        className={cn(
                          "grid gap-3.5",
                          isSingleCol ? "grid-cols-1" : "grid-cols-1 sm:grid-cols-2"
                        )}
                      >
                        {block.entries.map((entry) => (
                          <AnalysisBlockEntry
                            key={`${block.id}-${entry.key}`}
                            entry={entry}
                            blockId={block.id}
                          />
                        ))}
                      </div>
                    );
                  })()}
                </section>
              );
            })}
          </div>
        )}

        {/* Visualizers Stack */}
        {analysis.intentRatios && (
          <div className="pt-4 border-t border-slate-100">
            <RatioVisualizer intentRatios={analysis.intentRatios} />
          </div>
        )}

        {analysis.postType && (
          <div className="pt-4 border-t border-slate-100">
            <MultiLabelVisualizer
              postType={analysis.postType}
              commentThemes={analysis.commentThemes}
            />
          </div>
        )}

        {analysis.politicians && (
          <div className="pt-4 border-t border-slate-100">
            <AccordionVisualizer
              politicians={analysis.politicians}
              comments={comments}
            />
          </div>
        )}
      </div>
    </div>
  );
}
